version: "3"
services:
  web:
    # replace username/repo:tag w/ ya name & image details
    image: samnnodim/hello-python
    deploy:
      replicas: 5
      resources:
        limits:
          # use at max 10%
          cpus: "0.1"
          # use at most 50M of RAM
          memory: 50M 
      restart_policy:
        condition: on-failure
    ports:
      # map 80 on the host to the web's port 80 
      - "80:80"
    networks:
      - webnet
networks:
  webnet: